services:
  - type: web
    name: library
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/services:
  - type: web
    name: library
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/zwhLibrary-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        fromDatabase:
          name: zwelibrary_ocg0_6203
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: zwelibrary
          property: username
      - key: DB_PASS
        fromDatabase:
          name: zwelibrary
          property: password

databases:
  - name: library
    databaseName: zwelibrary_ocg0_6203
    user: zwelibrary_user
